
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Sep 07 21:46:37 CEST 2007
//----------------------------------------------------

package no.ntnu.xqft.parse;

/** CUP generated class containing symbol constants. */
public class XQFTSymbols {
  /* terminals */
  public static final int MINUS = 3;
  public static final int DECIMAL = 8;
  public static final int CHARACTER = 5;
  public static final int NUMBER = 7;
  public static final int DQUOTE = 4;
  public static final int EOF = 0;
  public static final int PLUS = 2;
  public static final int error = 1;
  public static final int WORD = 6;
}

